FROM grafana/grafana:latest
# COPY provisioning/dashboards/default.yaml /etc/grafana/provisioning/dashboards/default.yaml
RUN mkdir -p /var/lib/grafana/dashboards
# COPY ../../dashboards/grafana-prometheus.json /var/lib/grafana/dashboards/
EXPOSE 3000