global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape-configs:
  - job-name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.130.132:8080"]